// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iiwehgtrlnzkyylishbi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlpd2VoZ3RybG56a3l5bGlzaGJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwOTM5OTcsImV4cCI6MjA2NjY2OTk5N30.nWBCulIKmh8cRK-1LXt5HI1Z6GtHIaHyUe47387uRr4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);